# Generated by Django 5.2.1 on 2025-11-29 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_category_dietaryrestriction_ingredient_pantry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pantry',
            name='name',
            field=models.CharField(default='Principal', help_text='Nombre lógico: refri, almacén, congelador, etc.', max_length=100),
        ),
        migrations.AlterField(
            model_name='pantryingredient',
            name='date_aggregate',
            field=models.DateField(help_text='Fecha de ingreso a la despensa'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='portions',
            field=models.PositiveIntegerField(default=1, help_text='Número de personas'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='preparation_time',
            field=models.PositiveIntegerField(help_text='Tiempo total en minutos'),
        ),
        migrations.AlterField(
            model_name='steprecipe',
            name='estimated_time',
            field=models.PositiveIntegerField(blank=True, help_text='Tiempo estimado de este paso en minutos', null=True),
        ),
    ]
