# Generated by Django 5.2.1 on 2025-11-29 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_pantry_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, help_text='Imagen principal de la receta', null=True, upload_to='recipes/'),
        ),
    ]
