# Generated by Django 5.2.7 on 2025-12-02 04:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_recipe_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='dietaryrestriction',
            options={'ordering': ['user', 'ingredient'], 'verbose_name': 'Dietary Restriction', 'verbose_name_plural': 'Dietary Restrictions'},
        ),
        migrations.AlterModelOptions(
            name='ingredient',
            options={'ordering': ['name'], 'verbose_name': 'Ingredient', 'verbose_name_plural': 'Ingredients'},
        ),
        migrations.AlterModelOptions(
            name='pantry',
            options={'ordering': ['user', 'name'], 'verbose_name': 'Pantry', 'verbose_name_plural': 'Pantries'},
        ),
        migrations.AlterModelOptions(
            name='pantryingredient',
            options={'ordering': ['pantry', 'ingredient'], 'verbose_name': 'Pantry Ingredient', 'verbose_name_plural': 'Pantry Ingredients'},
        ),
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['-date_register'], 'verbose_name': 'Recipe', 'verbose_name_plural': 'Recipes'},
        ),
        migrations.AlterModelOptions(
            name='recipeingredient',
            options={'ordering': ['recipe', 'order'], 'verbose_name': 'Recipe Ingredient', 'verbose_name_plural': 'Recipe Ingredients'},
        ),
        migrations.AlterModelOptions(
            name='steprecipe',
            options={'ordering': ['recipe', 'id'], 'verbose_name': 'Recipe Step', 'verbose_name_plural': 'Recipe Steps'},
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, help_text='Imagen principal de la receta', null=True, upload_to='uploads/images/'),
        ),
        migrations.AlterField(
            model_name='steprecipe',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/steps/'),
        ),
        migrations.AlterModelTable(
            name='category',
            table='category',
        ),
        migrations.AlterModelTable(
            name='dietaryrestriction',
            table='dietary_restriction',
        ),
        migrations.AlterModelTable(
            name='ingredient',
            table='ingredient',
        ),
        migrations.AlterModelTable(
            name='pantry',
            table='pantry',
        ),
        migrations.AlterModelTable(
            name='pantryingredient',
            table='pantry_ingredient',
        ),
        migrations.AlterModelTable(
            name='recipe',
            table='recipe',
        ),
        migrations.AlterModelTable(
            name='recipeingredient',
            table='recipe_ingredient',
        ),
        migrations.AlterModelTable(
            name='steprecipe',
            table='step_recipe',
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.URLField(blank=True, help_text='URL de la foto de perfil (Google OAuth)', max_length=500)),
                ('bio', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'db_table': 'user_profile',
            },
        ),
        migrations.CreateModel(
            name='FavoriteRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='api.recipe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Favorite Recipe',
                'verbose_name_plural': 'Favorite Recipes',
                'db_table': 'favorite_recipe',
                'ordering': ['-date_added'],
                'unique_together': {('user', 'recipe')},
            },
        ),
    ]
