# Generated by Django 5.2.7 on 2025-12-02 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Categoría', 'verbose_name_plural': 'Categorías'},
        ),
        migrations.AlterModelOptions(
            name='ingredient',
            options={'ordering': ['name'], 'verbose_name': 'Ingrediente', 'verbose_name_plural': 'Ingredientes'},
        ),
    ]
