# Generated by Django 5.2.7 on 2025-12-18 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_category_options_alter_ingredient_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='classification',
            field=models.CharField(blank=True, choices=[('Verduras', 'Verduras'), ('Frutas', 'Frutas'), ('Granos y legumbres', 'Granos y legumbres'), ('Lácteos', 'Lácteos'), ('Proteínas animales', 'Proteínas animales'), ('Condimentos y salsas', 'Condimentos y salsas'), ('Bebidas', 'Bebidas'), ('Cereales y Masas', 'Cereales y Masas'), ('Otros', 'Otros')], default='Otros', max_length=100),
        ),
    ]
