# Generated by Django 5.2.7 on 2025-12-18 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_ingredient_classification'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pantryingredient',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='pantryingredient',
            name='date_aggregate',
            field=models.DateField(blank=True, help_text='Fecha de ingreso a la despensa', null=True),
        ),
    ]
