# Generated by Django 5.2.7 on 2025-12-18 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_pantryingredient_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pantryingredient',
            name='classification',
            field=models.CharField(choices=[('Verduras', 'Verduras'), ('Frutas', 'Frutas'), ('Granos y legumbres', 'Granos y legumbres'), ('Lácteos', 'Lácteos'), ('Proteínas animales', 'Proteínas animales'), ('Condimentos y salsas', 'Condimentos y salsas'), ('Bebidas', 'Bebidas'), ('Cereales y Masas', 'Cereales y Masas'), ('Otros', 'Otros')], default='Otros', max_length=100),
        ),
    ]
