# Generated by Django 5.2.7 on 2025-12-19 05:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_pantryingredient_classification'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pantryingredient',
            unique_together={('pantry', 'ingredient', 'date_aggregate')},
        ),
        migrations.AlterField(
            model_name='pantryingredient',
            name='date_aggregate',
            field=models.DateField(default=django.utils.timezone.now, help_text='Fecha de ingreso a la despensa'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='pantryingredient',
            name='classification',
        ),
    ]
